
trigger:
  branches:
    include:
    - '*'
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- script: |
    yarn
  displayName: 'Install dependencies'

- script: |
    yarn test:unit
  displayName: 'Run Unit tests'

- script: |
    yarn test:integration
  displayName: 'Run Integration tests'
