name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        uses: nuxt/actions-yarn@node-10
        with:
          args: install # will run `yarn install` command
      - name: yarn test
        uses: nuxt/actions-yarn@node-10
        with:
          args: test # will run `yarn test` command
