name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nuxt/actions-yarn@node-10
        with:
          cmd: install # will run `yarn install` command
      - uses: nuxt/actions-yarn@node-10
        with:
          cmd: test # will run `yarn test` command
